/* @flow */

export const round12 = [
  {
    home: 'Girona',
    away: 'Real Sociedad',
    rating: 0,
	time: '2:00',
	day: '18.11',
    homeLogo: null,
    awayLogo: null,
  },
  {
    home: 'Getafe',
    away: 'Alaves',
	time: '18:00',
	day: '18.11',
    rating: 0,
    homeLogo: null,
    awayLogo: null,
  },
  {
    home: 'Leganes',
    away: 'Barcelona',
	time: '21:15',
	day: '18.11',
    rating: 0,
    homeLogo: null,
    awayLogo: null,
  },
  {
    home: 'Sevilla',
    away: 'Celta',
	time: '23:30',
	day: '18.11',
    rating: 0,
    homeLogo: null,
    awayLogo: null,
  },
  {
    home: 'Atletico Madrid',
    away: 'Real Madrid',
	time: '1:45',
	day: '19.11',
    rating: 0,
    homeLogo: null,
    awayLogo: null,
  },
  {
    home: 'Malaga',
    away: 'Deportivo',
	time: '17:00',
	day: '19.11',
    rating: 0,
    homeLogo: null,
    awayLogo: null,
  },
  {
    home: 'Espanyol',
    away: 'Valencia',
	time: '21:15',
	day: '19.11',
    rating: 0,
    homeLogo: null,
    awayLogo: null,
  },
  {
    home: 'Las Palmas',
    away: 'Levante',
	time: '23:30',
	day: '19.11',
    rating: 0,
    homeLogo: null,
    awayLogo: null,
  },
  {
    home: 'Athletic Bilbao',
    away: 'Villareal',
    rating: 0,
	time: '1:45',
	day: '20.11',
    homeLogo: null,
    awayLogo: null,
  },
  {
    home: 'Eibar',
    away: 'Betis',
	time: '2:00',
	day: '21.11',
    rating: 0,
    homeLogo: null,
    awayLogo: null,
  }
];
